#:kivy 2.0.0

Calculator:
<Calculator>:
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        Label:
            text: root.ans
            font_size: 200
            text_size: self.size
            halign: 'right'
            valign: 'middle'
        GridLayout:
            cols: 4
            rows: 4
            size_hint_y: 4

            Button:
                text:'AC'
                on_press: root.AcButton()
            Button:
                text:'+/-' 
            Button:
                text:'C'
                on_press: root.CButton()
            Button:
                text:'+'
                on_press: root.plusButton()
            Button:
                text:'9'
                on_press: root.numberButton(9)
            Button:
                text:'8'
                on_press: root.numberButton(8)
            Button:
                text:'7'  
                on_press: root.numberButton(7)
            Button:
                text:'-'
                on_press: root.minusButton()
            Button:
                text:'6'
                on_press: root.numberButton(6)
            Button:
                text:'5'
                on_press: root.numberButton(5)
            Button:
                text:'4'
                on_press: root.numberButton(4)  
            Button:
                text:'×'
                on_press: root.multipleButton()
            Button:
                text:'3'
                on_press: root.numberButton(3)
            Button:
                text:'2'
                on_press: root.numberButton(2)
            Button:
                text:'1'
                on_press: root.numberButton(1)
            Button:
                text:'÷'
                on_press: root.divideButton()

        BoxLayout:
            Button:
                text:'0'
                on_press: root.numberButton(0)
                size_hint_x: 2
            Button:
                text:'.'
                
            Button:
                text:'='
                on_press: root.equalButton()


